# Change these first
owner: spschweiz
repo: status

sites:
  - name: SP Schweiz-Webseite
    url: https://www.sp-ps.ch
  - name: Wordpress-Plattform
    url: https://sp-parl.ch
  - name: Mitgliederdatenbank
    url: https://login.sp-ps.ch/tocco
  - name: Mobilisierungstool Avanti
    url: tel.sp-ps.ch
  - name: Mattermost
    url: https://mattermost.sp-ps.ch
  - name: Jitsi Meet SP Schweiz
    url: https://meet.sp-ps.ch

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.spschweiz.ch
  # baseUrl: /SP-Schweiz-Uptime-Monitor
  logoUrl: https://www.sp-ps.ch/sites/all/themes/sp_ps/logo.png
  name: SP Schweiz Statuspage
  introTitle: "Prüfe die Verfügbarkeit unserer Services."
  introMessage: "Bei Downtime ohne Ankündigung [bitte hier melden](https://github.com/spschweiz/status/issues)."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
