# Change these first
owner: spschweiz # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

ites:
  - name: SP Schweiz-Webseite
    url: https://www.sp-ps.ch
  - name: Wordpress-Plattform
    url: https://sp-parl.ch
  - name: Tocco
    url: https://login.sp-ps.ch/tocco
  - name: Mattermost Chat
    url: https://mattermost.sp-ps.ch
  - name: Jitsi Meet
    url: https://meet.sp-ps.ch

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.spschweiz.ch
  # baseUrl: /your-repo-name
  logoUrl: "https://www.sp-ps.ch/sites/all/themes/sp_ps/logo.png"
  name: Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
