owner: spschweiz
repo: status

sites:
  - name: SP Schweiz-Webseite
    url: https://www.sp-ps.ch
    icon: https://sp-parl.ch/wp-content/themes/sp/img/icons/apple-touch-icon.png
  - name: Wordpress-Plattform
    url: https://sp-parl.ch
    icon: https://s1.wp.com/i/favicon.ico
  - name: Mitgliederdatenbank
    url: https://login.sp-ps.ch/tocco
    icon: https://raw.githubusercontent.com/spschweiz/status/master/assets/rose.ico
    assignees: anweibel
  - name: Sektionsportal
    url: https://login.sp-ps.ch/
    icon: https://raw.githubusercontent.com/spschweiz/status/master/assets/hammer-and-wrench.ico
    assignees:
      - anweibel
    expectedStatusCodes:
      - 200
      - 401
  - name: Mobilisierungstool Avanti
    url: $URL_AVANTI
    icon: https://raw.githubusercontent.com/spschweiz/status/master/assets/raised-fist.ico
    assignees:
      - anweibel
  - name: Mattermost Chat
    url: https://mattermost.sp-ps.ch
    icon: https://mattermost.sp-ps.ch/static/images/favicon/favicon-default-16x16.png
  - name: Jitsi Meet SP Schweiz
    url: $URL_JITSI
    icon: https://meet.sp-ps.ch/images/favicon.ico
  - name: Telefonanlage
    url: $URL_PBX
    icon: https://raw.githubusercontent.com/spschweiz/status/master/assets/telephone.ico
  - name: Wissensdatenbank (Bücherregal)
    url: $URL_BOOKS
    icon: https://raw.githubusercontent.com/spschweiz/status/master/assets/books.ico
  - name: Terminalserver
    url: $URL_TS
    icon: https://raw.githubusercontent.com/spschweiz/status/master/assets/desktop-computer.png
  - name: Microsoft Exchange (Email, Kalender, Kontakte)
    url: $URL_EXCHANGE
    icon: https://raw.githubusercontent.com/spschweiz/status/master/assets/email.png
    assignees:
      - tsueri
assignees:
  - tsueri
status-website:
  cname: status.spschweiz.ch
  logoUrl: https://raw.githubusercontent.com/spschweiz/status/master/assets/sp-logo.png
  name: SP Schweiz Statuspage
  favicon: https://github.com/spschweiz/status/blob/master/assets/rose.ico
  introTitle: "Prüfe die Verfügbarkeit unserer Services"
  introMessage: "Bei Downtime ohne Ankündigung [bitte hier melden](https://github.com/spschweiz/status/issues)."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Support
      href: https://sp-ps.ch/support
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
i18n:
  activeIncidents: Aktive Vorfälle
  allSystemsOperational: Alle Systeme laufen störungsfrei.
  incidentReport: "Vorfall #$NUMBER Report →"
  activeIncidentSummary: Eröffnet am $DATE mit $POSTS Beiträgen
  incidentTitle: Vorfall $NUMBER Details
  incidentDetails: Vorfall Details
  incidentFixed: repariert
  incidentOngoing: andauernd
  incidentOpenedAt: eröffnet am
  incidentClosedAt: Geschlossen am
  incidentSubscribe: Updates abonnieren
  incidentViewOnGitHub: Auf GitHub anschauen
  incidentCommentSummary: Veröffentlicht am $DATE von $AUTHOR
  incidentBack: ← Zurück zu allen Vorfällen
  pastIncidents: Vergangene Vorfälle
  pastIncidentsResolved: Gelöst in $MINUTES Minuten mit $POSTS posts
  liveStatus: Live Status
  overallUptime: "Gesamte Verfügbarkeit: $UPTIME"
  overallUptimeTitle: Gesamte Verfügbarkeit
  averageResponseTime: "Durchschnittliche Antwortzeit: $TIMEms"
  averageResponseTimeTitle: Durchschnittliche Antwortzeit
  sevelDayResponseTime: 7-Tage Antwortzeit
  responseTimeMs: Antwortzeit (ms)
  up: verfügbar
  down: nicht verfügbar
  degraded: Service degradiert
  ms: ms
  loading: am laden
  navGitHub: GitHub
  footer: Für Alle statt für Wenige
  rateLimitExceededTitle: Ratengrenze überschritten
  rateLimitExceededIntro: Sie haben die Ratengrenze überschritten (Request/h). Sie müssen nun warten, bis sie diese Seite erneut besuchen dürfen. Alternativ fügen Sie ein GitHub Personal Access Token hinzu, um diese Seite zu besuchen.
  rateLimitExceededWhatDoesErrorMean: Was bedeutet dieser Fehler?
  rateLimitExceededErrorMeaning: Diese Webseite verwendet die GitHub API um auf Echtzeitdaten über Ihre Webseite zuzugreifen. Standardmässig erlaubt Github 60 Anfragen pro Minute, was Sie nun erreicht haben.
  rateLimitExceededErrorHowCanFix: Wie kann ich es lösen?
  rateLimitExceededErrorFix: Sie können eine Stunde warten oder Sie fügen ein GitHub Personal Access Token hinzu, das Ihnen 5'000 zusätzliche Anfragen pro Stunde ermöglicht.
  rateLimitExceededGeneratePAT: Lernen Sie mehr wie man ein persönliches Access Token generiert.
  rateLimitExceededHasSet: Sie haben ein persönliches Access Token gesetzt.
  rateLimitExceededRemoveToken: Token entfernen
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Ihr Token kopieren und einfügen
  rateLimitExceededSaveToken: Token speichern
  errorTitle: Ein Fehler ist aufgetreten
  errorIntro: Ein Fehler ist aufgetreten beim Versuch, die letzten Status-Details abzurufen.
  errorText: Sie können es in einem Moment erneut veruchen.
  errorHome: Gehen Sie zur Homepage
  pastScheduledMaintenance: Vergangene geplante Wartungen
  scheduledMaintenance: Geplante Wartungen
  scheduledMaintenanceSummaryStarted: Gestartet am $DATE für $DURATION Minuten
  scheduledMaintenanceSummaryStarts: Startet am $DATE für $DURATION Minuten
  startedAt: Gestartet am
  startsAt: Startet am
  duration: Dauer
  durationMin: $DURATION Minuten
  incidentCompleted: Abgeschlossen
  incidentScheduled: Geplant
  url: "URL"
  status: "Status"
  history: "Geschichte"
  responseTime: "Antwortzeit"
  responseTimeGraphAlt: "Antwortzeit Grafik"
  responseTimeDay: "24-Stunden Antwortzeit"
  responseTimeWeek: "7-Tage Antwortzeit"
  responseTimeMonth: "30-Tage Antwortzeit"
  responseTimeYear: "1-Jahr Antwortzeit"
  uptime: "Gesamtverfügbarkeit"
  uptimeDay: "24-Stunden Verfügbarkeit"
  uptimeWeek: "7-Tage Verfügbarkeit"
  uptimeMonth: "30-Tage Verfügbarkeit"
  uptimeYear: "1-Jahres Verfügbarkeit"
  liveStatusHtmlComment: "<!--live status-->"
  degradedPerformance: "🟨 Leistung degradiert"
  completeOutage: "🟥 Kompletter Ausfall"
  partialOutage: "🟧 Teilausfall"
