owner: spschweiz
repo: status

sites:
  - name: SP Schweiz-Webseite
    url: https://www.sp-ps.ch
  - name: Wordpress-Plattform
    url: https://sp-parl.ch
  - name: Mitgliederdatenbank
    url: https://login.sp-ps.ch/tocco
  - name: Mobilisierungstool Avanti
    url: tel.sp-ps.ch
  - name: Mattermost
    url: https://mattermost.sp-ps.ch
  - name: Jitsi Meet SP Schweiz
    url: https://meet.sp-ps.ch
assignees:
  - tsueri
status-website:
  cname: status.spschweiz.ch
  logoUrl: https://www.sp-ps.ch/sites/all/themes/sp_ps/logo.png
  name: SP Schweiz Statuspage
  introTitle: "Prüfe die Verfügbarkeit unserer Services"
  introMessage: "Bei Downtime ohne Ankündigung [bitte hier melden](https://github.com/spschweiz/status/issues)."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Support
      href: https://sp-ps.ch/support
